In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv("D:\\Datascience\\DataSets\\Students.csv")
df.head()

Background  Machine Learning  Python Remark
0       Tech              78.0    98.0   Pass
1       Tech               NaN    10.0   Fail
2   Non-Tech              69.0     NaN   Pass
3   Non-Tech              76.0    56.0   Pass
4       Tech               NaN     NaN   Pass

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Background        10 non-null     object 
 1   Machine Learning  6 non-null      float64
 2   Python            7 non-null      float64
 3   Remark            10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


# Dividing the Data Set into X and Y

In [4]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [5]:
x

array([['Tech', 78.0, 98.0],
       ['Tech', nan, 10.0],
       ['Non-Tech', 69.0, nan],
       ['Non-Tech', 76.0, 56.0],
       ['Tech', nan, nan],
       ['Tech', 20.0, 40.0],
       ['Tech', nan, 10.0],
       ['Non-Tech', 54.0, 20.0],
       ['Tech', 87.0, 98.0],
       ['Non-Tech', nan, nan]], dtype=object)

In [6]:
y

array(['Pass', 'Fail', 'Pass', 'Pass', 'Pass', 'Fail', 'Fail', 'Pass',
       'Pass', 'Fail'], dtype=object)

# Handling Missing Values using Simple Imputer

In [7]:
from sklearn.impute import SimpleImputer

In [8]:
si=SimpleImputer(missing_values=np.nan,strategy='mean')

In [9]:
si.fit(x[:,1:])

SimpleImputer()

In [10]:
x[:,1:] = si.transform(x[:,1:])

In [11]:
x

array([['Tech', 78.0, 98.0],
       ['Tech', 64.0, 10.0],
       ['Non-Tech', 69.0, 47.42857142857143],
       ['Non-Tech', 76.0, 56.0],
       ['Tech', 64.0, 47.42857142857143],
       ['Tech', 20.0, 40.0],
       ['Tech', 64.0, 10.0],
       ['Non-Tech', 54.0, 20.0],
       ['Tech', 87.0, 98.0],
       ['Non-Tech', 64.0, 47.42857142857143]], dtype=object)

# One hot Encoding for Features

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [13]:
ct = ColumnTransformer(transformers= [('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array( ct.fit_transform(x) )


In [14]:
x

array([[0.0, 1.0, 78.0, 98.0],
       [0.0, 1.0, 64.0, 10.0],
       [1.0, 0.0, 69.0, 47.42857142857143],
       [1.0, 0.0, 76.0, 56.0],
       [0.0, 1.0, 64.0, 47.42857142857143],
       [0.0, 1.0, 20.0, 40.0],
       [0.0, 1.0, 64.0, 10.0],
       [1.0, 0.0, 54.0, 20.0],
       [0.0, 1.0, 87.0, 98.0],
       [1.0, 0.0, 64.0, 47.42857142857143]], dtype=object)

# Label Encoding for Targets

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [16]:
y

array([1, 0, 1, 1, 1, 0, 0, 1, 1, 0])

# Splitting the dataset into Training Data and Testing Data

In [22]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=0)

# Feature Scaling with Standard Scaler

In [23]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()


In [24]:
from  sklearn.preprocessing import StandardScaler
sc=StandardScaler()

xtrain[:,2:]=sc.fit_transform(xtrain[:,2:])
xtest[:,2:]=sc.fit_transform(xtest[:,2:])

In [25]:
xtrain

array([[0.0, 1.0, 0.2074130978310859, 0.2323693217003598],
       [1.0, 0.0, 0.2074130978310859, 0.2323693217003598],
       [0.0, 1.0, 0.2074130978310859, -1.1434671141300194],
       [0.0, 1.0, 0.2074130978310859, -1.1434671141300194],
       [1.0, 0.0, -0.38519575311487386, -0.775877226694422],
       [1.0, 0.0, 0.9185437189662377, 0.547446368073729],
       [0.0, 1.0, 1.0370654891554296, 2.0913238953032387],
       [0.0, 1.0, -2.400065846331137, -0.04069745182322702]], dtype=object)

In [26]:
xtest

array([[1.0, 0.0, -1.0, -1.0000000000000002],
       [0.0, 1.0, 1.0, 0.9999999999999997]], dtype=object)